all: sudokuSolver

sudokuSolver:
	g++ -o sudokuSolver sudokuSolver.cc
	
test0:
	./sudokuSolver < board0.in

test1:
	./sudokuSolver < board1.in

test2:
	./sudokuSolver < board2.in
  
clean:
	rm sudokuSolver
